services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ft_transcendence-network

networks:
  ft_transcendence-network:
    driver: bridge
